### ISSUE TITLE
ask questions

### ISSUE THREAD

**Issue by Lan-ce-lot** [pschiffe/azure-ansible#2]
> Currently it's not possible to provide custom options for KUBELET_ARGS in /etc/kubernetes/kubelet file. So for example, if I want my pods to run with host network (KUBELET_ARGS="--host-network-sources=*"), I have to manually edit /etc/kubernetes/kubelet file on every node.

https://github.com/kubernetes-retired/contrib/issues/1788

Hello, I'm looking for a way to make kubelet use host network instead of cni. And I find your issue, can you teach me how to do it? Thx.

**Comment by pschiffe** [comment]
hey @Lan-ce-lot, I was dealing with this a long time ago; and I think the k8s landscape changed a lot since then.

Anyway, I would suggest you to go with managed k8s cluster if possible, it's much more hassle free. On Azure there's [AKS](https://azure.microsoft.com/en-us/products/kubernetes-service)

If you need to create and manage your own k8s cluster, take a look at Cluster API - https://cluster-api.sigs.k8s.io/
It's a modern way how to deploy and manage k8s. There are providers for various envs, such as Azure - https://capz.sigs.k8s.io/introduction.html
And there's usually couple of options how to handle networking, ie to use pre-existing Azure vnet: https://capz.sigs.k8s.io/topics/custom-vnet.html

**Comment by Lan-ce-lot** [comment]
Thanks for your advice.
